'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

interface DripRow {
  age: number;
  year: number;
  monthlyCostOfLiving: number;
  /** Monthly cost of living with average inflation applied for this row (row 0 = base, row i = base * (1 + inflation/100)^i) */
  monthlyCostOfLivingWithInflation: number;
  monthlyDividends: number;
  monthlyContribution: number;
  totalContribution: number; // monthly dividends + monthly contribution (per month)
  /** Annual dividend growth rate (%) used in projection */
  annualDividendGrowthRatePct: number;
  /** Yearly dividend money generated by the growth rate (previous year's dividends × growth %) */
  yearlyDividendGrowthAmount: number;
  /** Base yearly dividends (row 0 = total; row i>0 = previous year total) so Total = this + additionalContribIncrease + growth */
  yearlyDividendsBase: number;
  /** Additional contribution dividend increase (dividends from new money) for this row */
  additionalContributionDividendIncrease: number;
  canLiveOffDividends: boolean;
}

export function RetirementByDividends() {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [rows, setRows] = useState<DripRow[]>([]);
  const [portfolioValue, setPortfolioValue] = useState<number>(0);
  const [totalAnnualDividend, setTotalAnnualDividend] = useState<number>(0);
  const [portfolioYieldPct, setPortfolioYieldPct] = useState<number>(0);
  const [usdToGbp, setUsdToGbp] = useState<number | null>(null);
  const [retirementInflation, setRetirementInflation] = useState<number>(3);
  const [askAiCopied, setAskAiCopied] = useState(false);
  /** Projection params (set on load, used by projection effect; yield is editable and not stored) */
  const [projMonthlyRetirement, setProjMonthlyRetirement] = useState<number>(5000);
  const [projMonthlyContribution, setProjMonthlyContribution] = useState<number>(500);
  const [projCurrentAge, setProjCurrentAge] = useState<number>(44);
  const [projInflationPct, setProjInflationPct] = useState<number>(3);
  const [projDividendGrowthPct, setProjDividendGrowthPct] = useState<number>(3);
  const [projectionReady, setProjectionReady] = useState(false);

  const currentYear = new Date().getFullYear();
  const currentMonth = new Date().getMonth() + 1;

  useEffect(() => {
    let cancelled = false;
    fetch('/api/usd-to-gbp')
      .then((res) => res.ok ? res.json() : null)
      .then((data) => {
        if (!cancelled && data?.rate != null && Number.isFinite(data.rate)) setUsdToGbp(Number(data.rate));
      })
      .catch(() => {});
    return () => { cancelled = true; };
  }, []);

  useEffect(() => {
    const fetchSettings = async () => {
      try {
        const response = await fetch('/api/settings');
        if (!response.ok) throw new Error('Failed to fetch settings');
        const data = await response.json();
        const settings = data.data || [];
        const getSetting = (key: string, defaultValue: number) => {
          const s = settings.find((x: { key: string }) => x.key === key);
          return s && s.value != null && s.value !== '' ? parseFloat(String(s.value)) : defaultValue;
        };
        const retirementCurrentAge = Math.floor(getSetting('retirement_current_age', 44));
        // Monthly cost of living: try MONTHLY_RETIERMENT_VALUE (as in settings) then MONTHLY_RETIREMENT_VALUE, default 5000
        const monthlyRetirementValue =
          getSetting('MONTHLY_RETIERMENT_VALUE', NaN) ||
          getSetting('MONTHLY_RETIREMENT_VALUE', 5000) ||
          5000;
        const monthlyContribution = getSetting('monthly_contribution', 500);
        setRetirementInflation(getSetting('retirement_inflation', 3));
        const dividendGrowthPct = getSetting('dividend_growth_rate', 3);
        setProjMonthlyRetirement(monthlyRetirementValue);
        setProjMonthlyContribution(monthlyContribution);
        setProjCurrentAge(retirementCurrentAge);
        setProjInflationPct(getSetting('retirement_inflation', 3));
        setProjDividendGrowthPct(dividendGrowthPct);

        const loadPortfolio = async () => {
          try {
            const res = await fetch('/api/etoro/portfolio/load?activeOnly=false');
            if (!res.ok) throw new Error('Failed to load portfolio');
            const portfolio = await res.json();
            const stocks = portfolio.stocks ?? [];
            const isDividend = (s: { isDividend?: boolean | string | null }) =>
              s.isDividend !== false && s.isDividend !== 'false';
            const dividendStocksOnly = stocks.filter(isDividend);
            let totalValue = 0;
            let totalYearlyDividend = 0;
            for (const s of dividendStocksOnly) {
              const price = Number(s.currentPrice);
              const shares = Number(s.sharesOwned);
              const dps = Number(s.dividendPerShare);
              if (Number.isFinite(price) && Number.isFinite(shares)) totalValue += price * shares;
              if (Number.isFinite(dps) && Number.isFinite(shares)) totalYearlyDividend += dps * shares;
            }

            setPortfolioValue(totalValue);
            setTotalAnnualDividend(totalYearlyDividend);
            const yieldPctDecimal = totalValue > 0 ? totalYearlyDividend / totalValue : 0;
            setPortfolioYieldPct(parseFloat((yieldPctDecimal * 100).toFixed(2)));
            setProjectionReady(true);
          } catch (e: unknown) {
            setError(e instanceof Error ? e.message : 'Failed to load portfolio');
            setRows([]);
          } finally {
            setLoading(false);
          }
        };

        await loadPortfolio();
      } catch (e: unknown) {
        setError(e instanceof Error ? e.message : 'Failed to load settings');
        setLoading(false);
      }
    };
    fetchSettings();
  }, []);

  useEffect(() => {
    if (!projectionReady || portfolioValue <= 0) return;
    const rateForLoop = usdToGbp ?? 0.8;
    const yieldPctDecimal = portfolioYieldPct / 100;
    const monthlyDividendsYear0 = totalAnnualDividend / 12;
    const tableRows: DripRow[] = [];
    let age = projCurrentAge;
    let year = currentYear;
    let monthlyDiv = monthlyDividendsYear0;
    let monthlyContrib = projMonthlyContribution;
    let previousYearlyDividends = 0;
    const maxYears = 200;

    for (let i = 0; i < maxYears; i++) {
      const yearlyDividends = monthlyDiv * 12;
      const yearlyDividendsBase = i === 0 ? yearlyDividends : previousYearlyDividends;
      const yearlyDividendGrowthAmount = i === 0 ? 0 : previousYearlyDividends * (projDividendGrowthPct / 100);
      const totalContribUsd = monthlyDiv + (rateForLoop > 0 ? monthlyContrib / rateForLoop : 0);
      const dividendsFromNewContributions = totalContribUsd * 12 * yieldPctDecimal;
      const totalContributionUsd = yearlyDividendsBase + dividendsFromNewContributions + yearlyDividendGrowthAmount;
      const monthlyAmountUsd = totalContributionUsd / 12;
      const monthlyAmountGbp = monthlyAmountUsd * rateForLoop;
      const monthlyCostWithInflation = projMonthlyRetirement * Math.pow(1 + projInflationPct / 100, i);
      const canLive = monthlyAmountGbp >= monthlyCostWithInflation;
      const totalContrib = monthlyDiv + monthlyContrib;

      tableRows.push({
        age,
        year,
        monthlyCostOfLiving: projMonthlyRetirement,
        monthlyCostOfLivingWithInflation: monthlyCostWithInflation,
        monthlyDividends: monthlyDiv,
        monthlyContribution: monthlyContrib,
        totalContribution: totalContrib,
        annualDividendGrowthRatePct: projDividendGrowthPct,
        yearlyDividendGrowthAmount,
        yearlyDividendsBase,
        additionalContributionDividendIncrease: dividendsFromNewContributions,
        canLiveOffDividends: canLive,
      });
      if (canLive) break;
      previousYearlyDividends = yearlyDividends;
      const yearlyDividendsNext = yearlyDividends * (1 + projDividendGrowthPct / 100) + dividendsFromNewContributions;
      monthlyDiv = yearlyDividendsNext / 12;
      age += 1;
      year += 1;
    }
    setRows(tableRows);
  }, [
    projectionReady,
    portfolioValue,
    totalAnnualDividend,
    portfolioYieldPct,
    projMonthlyRetirement,
    projMonthlyContribution,
    projCurrentAge,
    projInflationPct,
    projDividendGrowthPct,
    usdToGbp,
    currentYear,
  ]);

  const rate = usdToGbp ?? 1;
  /** Convert USD to GBP and format with £ */
  const formatCurrency = (n: number) =>
    Number.isFinite(n) ? `£${(n * rate).toLocaleString('en-GB', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : '—';
  /** Format value already in GBP with £ (no conversion) */
  const formatGbpOnly = (n: number) =>
    Number.isFinite(n) ? `£${n.toLocaleString('en-GB', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : '—';

  if (loading) {
    return <p className="text-gray-600 dark:text-gray-400">Loading...</p>;
  }

  const portfolioYieldPercent = portfolioValue > 0 ? (totalAnnualDividend / portfolioValue) * 100 : 0;
  // Additional Contribution Dividend Increase = 12 months × (monthly total contribution in USD) × (portfolio yield)
  const yearlyDividendIncrease = (monthlyTotalContribUsd: number) =>
    monthlyTotalContribUsd * 12 * (portfolioYieldPct / 100);

  const fmtGbp = (n: number) => Number.isFinite(n) ? `£${n.toLocaleString('en-GB', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : '—';
  const fmtUsdToGbp = (n: number) => Number.isFinite(n) ? `£${(n * rate).toLocaleString('en-GB', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : '—';

  const copyAskAiPrompt = async () => {
    const requiredMonthly = rows[0]?.monthlyCostOfLiving ?? 0;
    const monthlyContrib = rows[0]?.monthlyContribution ?? 0;
    const hitIndex = rows.findIndex((r) => r.canLiveOffDividends);
    const showRows = new Set<number>();
    for (let i = 0; i < Math.min(5, rows.length); i++) showRows.add(i);
    if (hitIndex >= 0) {
      for (let j = Math.max(0, hitIndex - 2); j <= Math.min(hitIndex + 1, rows.length - 1); j++) showRows.add(j);
    } else {
      for (let i = 5; i < Math.min(12, rows.length); i++) showRows.add(i);
    }
    const sortedShow = Array.from(showRows).sort((a, b) => a - b);
    const lines: string[] = [
      'I have a retirement-by-dividends plan I\'d like you to review. All currency figures below are in GBP (£).',
      '',
      '**Summary**',
      `- Current Yearly Dividend: ${fmtUsdToGbp(totalAnnualDividend)}`,
      `- Current Dividend Portfolio Value: ${fmtUsdToGbp(portfolioValue)}`,
      `- Portfolio yield: ${portfolioValue > 0 ? portfolioYieldPercent.toFixed(2) : 'N/A'}%`,
      `- Required Monthly Dividend Income: ${fmtGbp(requiredMonthly)}`,
      `- Monthly Contribution: ${fmtGbp(monthlyContrib)}`,
      `- Average Inflation Rate: ${retirementInflation}%`,
      `- Annual dividend growth rate (projection): ${rows[0]?.annualDividendGrowthRatePct ?? 3}%`,
      '',
      '**Table key**',
      '- Yearly Dividends (total) = Yearly Dividends (base) + Additional Contribution Dividend Increase + Annual dividend growth.',
      '- Monthly Available Dividend Income = Yearly Dividends (total) ÷ 12.',
      '- Live Off Dividends = Yes when Monthly Available Dividend Income ≥ Monthly Living Cost.',
      '',
      '**Projection (selected rows)**',
      'Age/Year | Yearly Dividends (base) | Additional Contribution Dividend Increase | Annual dividend growth | Yearly Dividends (total) | Monthly Available Dividend Income | Monthly Living Cost | Live Off Dividends',
    ];
    sortedShow.forEach((idx) => {
      const r = rows[idx];
      if (!r) return;
      const totalContrib = r.yearlyDividendsBase + r.additionalContributionDividendIncrease + r.yearlyDividendGrowthAmount;
      const monthlyAmt = totalContrib / 12;
      lines.push(
        `${r.age}/${r.year} | ${fmtUsdToGbp(r.yearlyDividendsBase)} | ${fmtUsdToGbp(r.additionalContributionDividendIncrease)} | ${fmtUsdToGbp(r.yearlyDividendGrowthAmount)} | ${fmtUsdToGbp(totalContrib)} | ${fmtUsdToGbp(monthlyAmt)} | ${fmtGbp(r.monthlyCostOfLivingWithInflation)} | ${r.canLiveOffDividends ? 'Yes' : 'No'}`
      );
    });
    lines.push('', 'Please:');
    lines.push('1. Validate whether the numbers and assumptions look consistent.');
    lines.push('2. Tell me if you think this plan is sensible.');
    lines.push('3. Offer specific suggestions on how to improve the plan (e.g. save more, adjust timeline, diversify, tax efficiency, or other ideas).');
    const prompt = lines.join('\n');
    try {
      await navigator.clipboard.writeText(prompt);
      setAskAiCopied(true);
      setTimeout(() => setAskAiCopied(false), 2000);
    } catch {
      setAskAiCopied(false);
    }
  };

  return (
    <div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
          <div className="p-4 bg-white dark:bg-gray-800 rounded-lg shadow border border-gray-200 dark:border-gray-600">
            <div className="text-sm font-medium text-gray-600 dark:text-gray-400 mb-1">Current Yearly Dividend</div>
            <div className="text-2xl font-bold text-gray-900 dark:text-white">{formatCurrency(totalAnnualDividend)}</div>
          </div>
          <div className="p-4 bg-white dark:bg-gray-800 rounded-lg shadow border border-gray-200 dark:border-gray-600">
            <div className="text-sm font-medium text-gray-600 dark:text-gray-400 mb-1">Current Dividend Portfolio Value</div>
            <div className="text-2xl font-bold text-gray-900 dark:text-white">{formatCurrency(portfolioValue)}</div>
          </div>
          <div className="p-4 bg-white dark:bg-gray-800 rounded-lg shadow border border-gray-200 dark:border-gray-600">
            <div className="text-sm font-medium text-gray-600 dark:text-gray-400 mb-1">Portfolio Yield (%)</div>
            {portfolioValue > 0 ? (
              <div className="flex items-baseline gap-1">
                <input
                  type="number"
                  step="0.01"
                  min="0"
                  max="100"
                  value={portfolioYieldPct.toFixed(2)}
                  onChange={(e) => {
                    const v = parseFloat(e.target.value);
                    if (!Number.isNaN(v) && v >= 0 && v <= 100) setPortfolioYieldPct(parseFloat(v.toFixed(2)));
                  }}
                  onBlur={(e) => {
                    const v = parseFloat(e.target.value);
                    if (Number.isNaN(v) || v < 0) setPortfolioYieldPct(0);
                    else if (v > 100) setPortfolioYieldPct(100);
                    else setPortfolioYieldPct(parseFloat(v.toFixed(2)));
                  }}
                  className="w-24 text-2xl font-bold text-gray-900 dark:text-white bg-transparent border-b border-gray-300 dark:border-gray-500 focus:border-indigo-500 focus:outline-none py-1"
                />
                <span className="text-2xl font-bold text-gray-900 dark:text-white">%</span>
              </div>
            ) : (
              <div className="text-2xl font-bold text-gray-900 dark:text-white">N/A</div>
            )}
          </div>
        </div>

        {error && (
          <div className="mb-4 p-4 bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-300 rounded-lg">
            {error}
          </div>
        )}

        {/* Required Monthly Dividend Income, Monthly Contribution, Average Inflation Rate, Ask AI */}
        {rows.length > 0 && (
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-4">
            <div className="p-4 bg-white dark:bg-gray-800 rounded-lg shadow border border-gray-200 dark:border-gray-600">
              <div className="text-sm font-medium text-gray-600 dark:text-gray-400 mb-1">Required Monthly Dividend Income</div>
              <div className="text-xl font-bold text-gray-900 dark:text-white">{formatGbpOnly(rows[0].monthlyCostOfLiving)}</div>
            </div>
            <div className="p-4 bg-white dark:bg-gray-800 rounded-lg shadow border border-gray-200 dark:border-gray-600">
              <div className="text-sm font-medium text-gray-600 dark:text-gray-400 mb-1">Monthly Contribution</div>
              <div className="text-xl font-bold text-gray-900 dark:text-white">{formatGbpOnly(rows[0].monthlyContribution)}</div>
            </div>
            <div className="p-4 bg-white dark:bg-gray-800 rounded-lg shadow border border-gray-200 dark:border-gray-600">
              <div className="text-sm font-medium text-gray-600 dark:text-gray-400 mb-1">Average Inflation Rate</div>
              <div className="text-xl font-bold text-gray-900 dark:text-white">{retirementInflation}%</div>
            </div>
            <div className="p-4 bg-white dark:bg-gray-800 rounded-lg shadow border border-gray-200 dark:border-gray-600 flex items-center justify-center">
              <button
                type="button"
                onClick={copyAskAiPrompt}
                className="px-5 py-2.5 rounded-lg font-medium bg-indigo-600 text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 dark:focus:ring-offset-gray-800 transition-colors"
              >
                {askAiCopied ? 'Copied!' : 'Ask AI'}
              </button>
            </div>
          </div>
        )}

        <div className="bg-white dark:bg-gray-800 rounded-lg shadow overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full border-collapse">
              <thead>
                <tr className="bg-gray-100 dark:bg-gray-700 border-b border-gray-200 dark:border-gray-600">
                  <th className="text-center py-3 px-4 font-semibold text-gray-700 dark:text-gray-300">Age/Year</th>
                  <th className="text-center py-3 px-4 font-semibold text-gray-700 dark:text-gray-300">Yearly Dividends (base)</th>
                  <th className="text-center py-3 px-4 font-semibold text-gray-700 dark:text-gray-300">Additional Contribution Dividend Increase</th>
                  <th className="text-center py-3 px-4 font-semibold text-gray-700 dark:text-gray-300">Annual dividend growth</th>
                  <th className="text-center py-3 px-4 font-semibold text-gray-700 dark:text-gray-300">Yearly Dividends</th>
                  <th className="text-center py-3 px-4 font-semibold text-gray-700 dark:text-gray-300">Monthly Available Dividend Income</th>
                  <th className="text-center py-3 px-4 font-semibold text-gray-700 dark:text-gray-300">Monthly Living Cost</th>
                  <th className="text-center py-3 px-4 font-semibold text-gray-700 dark:text-gray-300">Live Off Dividends</th>
                </tr>
              </thead>
              <tbody>
                {rows.length === 0 ? (
                  <tr>
                    <td colSpan={8} className="text-center py-8 text-gray-500 dark:text-gray-400">
                      {error ? 'Unable to build projection.' : 'No data. Load portfolio on the Dividends page first.'}
                    </td>
                  </tr>
                ) : (
                  rows.map((r, i) => (
                    <tr
                      key={`${r.year}-${r.age}`}
                      className={`border-b border-gray-100 dark:border-gray-700 ${
                        r.canLiveOffDividends ? 'bg-green-50 dark:bg-green-900/20' : ''
                      }`}
                    >
                      <td className="py-3 px-4 text-center text-gray-900 dark:text-white">{r.age}/{r.year}</td>
                      <td className="py-3 px-4 text-center font-medium text-gray-900 dark:text-white">{formatCurrency(r.yearlyDividendsBase)}</td>
                      <td className="py-3 px-4 text-center text-gray-700 dark:text-gray-300">{formatCurrency(r.additionalContributionDividendIncrease)}</td>
                      <td className="py-3 px-4 text-center text-gray-700 dark:text-gray-300">{formatCurrency(r.yearlyDividendGrowthAmount)}</td>
                      <td className="py-3 px-4 text-center text-gray-700 dark:text-gray-300">
                        {formatCurrency(r.yearlyDividendsBase + r.additionalContributionDividendIncrease + r.yearlyDividendGrowthAmount)}
                      </td>
                      <td className="py-3 px-4 text-center text-gray-700 dark:text-gray-300">
                        {formatCurrency((r.yearlyDividendsBase + r.additionalContributionDividendIncrease + r.yearlyDividendGrowthAmount) / 12)}
                      </td>
                      <td className="py-3 px-4 text-center text-gray-700 dark:text-gray-300">{formatGbpOnly(r.monthlyCostOfLivingWithInflation)}</td>
                      <td className="py-3 px-4 text-center">
                        {r.canLiveOffDividends ? (
                          <span className="font-semibold text-green-600 dark:text-green-400">Yes</span>
                        ) : (
                          <span className="font-semibold text-red-600 dark:text-red-400">No</span>
                        )}
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
    </div>
  );
}

export default function RetirementByDividendsPage() {
  const router = useRouter();
  useEffect(() => {
    router.replace('/finances/retirement-by-target-pot?tab=dividends');
  }, [router]);
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-8 px-4 flex items-center justify-center">
      <p className="text-gray-600 dark:text-gray-400">Redirecting to Retirement Target…</p>
    </div>
  );
}
